name: suai_coursework_frontend
description: Flutter based frontend for SUAI coursework.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.5
  dio: ^5.3.3
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/"
    - "assets/icons/"

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/Nunito-Light.ttf
        - asset: fonts/Nunito/Nunito-Medium.ttf
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-SemiBold.ttf